### ISSUE TITLE
能否增加一个package.json文件，cordova安装无法完成

### ISSUE THREAD

**Issue by imyeah** [realidfarm/cordova-plugin-rfid#1]
不过我也不是很确定确安装问题是否由package.json文件引起。在线和下载到本地安装均无法完成。

这是报错信息：
`Error: Failed to fetch plugin https://github.com/realidfarm/cordova-plugin-rfid.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\FERRIN~1\AppData\Local\Temp\npm-15520-3f43749d\git-cache-b1ecea09\ab55900f30ca0aa03d87e9bb10d869cb1bd7d798
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/realidfarm/cordova-plugin-rfid.git" "--save"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\mobile-field-service\node_modules\npm-debug.log`

**Comment by taofengno1** [comment]
@imyeah package.json 我加上去了，你再试试

**Comment by imyeah** [comment]
这次可以正常安装了，谢谢你！我看你还有其他几个插件未有设置package.json，我觉得有时间可以一并处理下。

**Comment by taofengno1** [comment]
@imyeah 谢提醒，我抽空处理下
