### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by imyeah** [realidfarm/cordova-plugin-rfid#2]
下面是报错信息，^标记实际指向的是R.raw.shibai以及R.raw.duka3中的R对象后的点：
`:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\www\mobile-field-service\platforms\android\src\com\realidtek\rfid\Sound.java:34: ����: ������R������
                MediaPlayer player = MediaPlayer.create(context, R.raw.shibai);
                                                                  ^
D:\www\mobile-field-service\platforms\android\src\com\realidtek\rfid\Sound.java:56: ����: ������R������
                MediaPlayer player = MediaPlayer.create(context, R.raw.duka3);
                                                                  ^
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ���������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
2 ������
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace
 option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 4.215 secs
Error: cmd: Command failed with exit code 1 Error output:
D:\www\mobile-field-service\platforms\android\src\com\realidtek\rfid\Sound.java:34: ����: ������R������
                MediaPlayer player = MediaPlayer.create(context, R.raw.shibai);
                                                                  ^
D:\www\mobile-field-service\platforms\android\src\com\realidtek\rfid\Sound.java:56: ����: ������R������
                MediaPlayer player = MediaPlayer.create(context, R.raw.duka3);
                                                                  ^
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ���������ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

**Comment by taofengno1** [comment]
在Sound.java文件头部引入你的资源类 import com.xxx.xxx.R; 
com.xxx.xxx 特换成你项目的包名
（PS：这个插件是基于特定pda硬件读取低频耳标的，手机是用不了）

**Comment by imyeah** [comment]
好的，谢谢，我试下！
